CREATE TABLE Data (
   id INTEGER PRIMARY KEY,
   loc TEXT NOT NULL
);

CREATE TABLE Jobs (
   id INTEGER PRIMARY KEY,
   data_id INTEGER REFERENCES Data(id),
   params_loc TEXT NOT NULL,
   done INTEGER NOT NULL,
   dynamic_opt INTEGER NOT NULL
);